production:
  adapter: sqlite3
  database: db/database.sqlite3
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.database.sqlite3
  encoding: UTF8
  pool: 5
  timeout: 5000